# Temporal thresholds — single source of truth
# All values in days unless otherwise noted

CONVOCATION_DAYS_BEFORE_EXAM = 10
EXAM_IMMINENT_DAYS = 7
EXAM_WITHIN_DAYS = 30
SESSION_STARTS_SOON_DAYS = 3
CMA_CONTACT_URGENT_DAYS = 5
UBER_VERIFICATION_DELAY_DAYS = 4
FORCE_MAJEURE_DEADLINE_DAYS = 14
SESSION_MIN_DAYS_BEFORE_EXAM = 3
SESSION_MAX_DAYS_BEFORE_EXAM = 60
SESSION_LATE_JOIN_DAYS = 3
MAX_DATES_DISPLAYED = 5
RECENT_PROPOSAL_HOURS = 48
ANCIEN_DOSSIER_CUTOFF_DATE = '2025-11-01'
